### ISSUE TITLE
能否 Hook electron其他的api

### ISSUE THREAD

**Issue by XiaoMiku01** [mo-jinran/BetterQQNT#1]
`BrowserWindow`  能做的事有点少，只能改改ui。如果可以hook ipc 通信的话，就那做很多事了，比如防撤回啥的

**Comment by MicroCBer** [comment]
https://github.com/koishi-nt/BetterQQNT/ 已实现

**Comment by mo-jinran** [comment]
你可以自行编写插件去hook webContents.send，比如：
`
// 初始化
module.exports = webContents => {
    const original_send = webContents.send;
    webContents.send = function (channel, ...args) {
        console.log(channel, ...args);
        return original_send.call(webContents, channel, ...args);
    }
}
`
![image](https://github.com/mo-jinran/BetterQQNT/assets/66980784/451fdab3-1ddc-452e-8ae0-3a375c761ef4)
