### ISSUE TITLE
提交新主题

### ISSUE THREAD

**Issue by festoney8** [mo-jinran/BetterQQNT#15]
[BetterQQNT-Wechat-Theme](https://github.com/festoney8/BetterQQNT-Wechat-Theme)  一个超高仿微信风格的QQ主题（整活

一个小问题，目前plugins目录下所有插件都默认启用，有可能会出现插件冲突（如主题css冲突），想禁用插件需要从目录移除文件夹并重启QQ
未来是否考虑给BetterQQNT新增一个管理页面，在设置中手动设定各个plugin是否启用？

**Comment by mo-jinran** [comment]
正在做了，这两天就在完善配置界面
