### ISSUE TITLE
QQNT数据库路径

### ISSUE THREAD

**Issue by valetzx** [mo-jinran/BetterQQNT#17]
默认qqnt会有一部分数据存在 ` \Document\Tencent Files ` 文件夹，请问有没有什么方法能把这个路径迁到别的地方，因为qq开着文件会占用，onedrive自动同步会卡住(

**Comment by mo-jinran** [comment]
QQNT本身的事情，不属于项目，标记为无效

**Comment by mo-jinran** [comment]
如果你之前安装的PCQQ有修改目录位置，那么新安装的QQNT会使用那个位置

**Comment by valetzx** [comment]
好的信息

**Comment by FW27623** [comment]
> 默认qqnt会有一部分数据存在 `\Document\Tencent Files` 文件夹，请问有没有什么方法能把这个路径迁到别的地方，因为qq开着文件会占用，onedrive自动同步会卡住(

找到这个路径：`"C:\Users\Public\Documents\Tencent\QQ\UserDataInfo.ini"`，然后把 UserDataSavePathType 等于后面的数字改成 2，UserDataSavePath 等于后面的路径替换成你想要的路径，然后重启QQ看看文件有没有转移，如果没有手动搬过去就行了，我个人测试有效。

UserDataSavePathType= 后的数字1表示存储到C盘我的文档文件夹；2是代表保存到自定义路径；0是保存到安装文件夹，当前版本不一定可用
UserDataSavePath= 后的路径表示保存到 F:\Tencent\Document 文件夹

```
[UserDataSet]
UserDataSavePathType=2
UserDataSavePath=F:\Tencent\Document
```

**Comment by valetzx** [comment]
OK 谢谢，已成功迁移

**Comment by FW27623** [comment]
> OK 谢谢，已成功迁移

没事，转移了就行

**Comment by StudentYee** [comment]
> > 默认qqnt会有一部分数据存在 `\Document\Tencent Files` 文件夹，请问有没有什么方法能把这个路径迁到别的地方，因为qq开着文件会占用，onedrive自动同步会卡住(
> 
> 找到这个路径：`"C:\Users\Public\Documents\Tencent\QQ\UserDataInfo.ini"`，然后把 UserDataSavePathType 等于后面的数字改成 2，UserDataSavePath 等于后面的路径替换成你想要的路径，然后重启QQ看看文件有没有转移，如果没有手动搬过去就行了，我个人测试有效。
> 
> UserDataSavePathType= 后的数字1表示存储到C盘我的文档文件夹；2是代表保存到自定义路径；0是保存到安装文件夹，当前版本不一定可用 UserDataSavePath= 后的路径表示保存到 F:\Tencent\Document 文件夹
> 
> ```
> [UserDataSet]
> UserDataSavePathType=2
> UserDataSavePath=F:\Tencent\Document
> ```

你好，请问一下微信有没有类似的操作
