### ISSUE TITLE
[Bug] 插件设置界面标题不会自动更新

### ISSUE THREAD

**Issue by xh321** [mo-jinran/BetterQQNT#21]
进入设置界面，先点击BetterQQNT再点击登录设置，标题还是BetterQQNT。先点击其他插件设置，再点击登陆设置，也是如此。
不影响使用，但强迫症（

**Comment by mo-jinran** [comment]
已知问题，随便点个插件的设置选项，再点击QQ的选项，再点回QQ选项即可触发

**Comment by mo-jinran** [comment]
这个bug我觉得应该没人会触发（毕竟藏得还是有点深的，我就没管它了（
