### ISSUE TITLE
macOS安装后报错

### ISSUE THREAD

**Issue by FredLin5** [mo-jinran/BetterQQNT#29]
<img width="632" alt="截屏" src="https://github.com/mo-jinran/BetterQQNT/assets/38588690/e605693b-321a-4f50-b62e-92151e39ab97">

如图，安装到 `/Applications/QQ.app/Contents/Resources/app` 并修改 `package.json` 后启动QQ报错。

**Comment by mo-jinran** [comment]
没有针对MacOS进行适配，没有设备，方便列出MacOS下QQ的目录结构吗？

**Comment by keta1** [comment]
拉取最新的 仓库试试，不要使用 release

**Comment by FredLin5** [comment]
> 没有针对MacOS进行适配，没有设备，方便列出MacOS下QQ的目录结构吗？

目录结构是这样的
[QQ.txt](https://github.com/mo-jinran/BetterQQNT/files/11934636/QQ.txt)

**Comment by FredLin5** [comment]
> 拉取最新的 仓库试试，不要使用 release

最新的仓库可以启动QQ了，不过BetterQQNT设置内没有内容，数据目录看起来也并没有在./Home/下创建

<img width="952" alt="截屏" src="https://github.com/mo-jinran/BetterQQNT/assets/38588690/7735e001-0d43-4e5a-8b5d-823e0b4019d2">

**Comment by mo-jinran** [comment]
能否在设置界面按F12开启DevTools？

**Comment by FredLin5** [comment]
> 能否在设置界面按F12开启DevTools？

可以开启，如图
<img width="952" alt="截屏" src="https://github.com/mo-jinran/BetterQQNT/assets/38588690/3f77df77-84f4-48dc-8d53-767290a1b952">

**Comment by mo-jinran** [comment]
拉取最新的仓库试试，设置界面应该修好了

**Comment by FredLin5** [comment]
原来设置界面是有内容的，用最新的仓库确实显示出内容和插件管理了
