### ISSUE TITLE
[bug] 环境变量修改插件目录貌似未生效

### ISSUE THREAD

**Issue by MoeBai** [mo-jinran/BetterQQNT#30]
Windows环境下,设置环境变量"BETTERQQNT_PROFILE"的值为"C:\BetterQQNT"后,QQ设置中的数据目录仍为:"用户/Documents/BetterQQNT"

**Comment by mo-jinran** [comment]
需完全重新启动QQNT才可生效

**Comment by MoeBai** [comment]
我修改路径之后接着重启电脑配置就生效了.

**Comment by AsakuraHitomi** [comment]
> Windows环境下,设置环境变量"BETTERQQNT_PROFILE"的值为"C:\BetterQQNT"后,QQ设置中的数据目录仍为:"用户/Documents/BetterQQNT"

请问如何设置环境变量 LITELOADERQQNT_PROFILE 数据路径，我不知道应该修改src下的哪一个文件。
