### ISSUE TITLE
提交主题

### ISSUE THREAD

**Issue by MUKAPP** [mo-jinran/BetterQQNT#4]
Hey，BetterQQNT 的作者😺
我基于您的 test-theme 写了 [MSpring主题](https://github.com/MUKAPP/BetterQQNT-MSpring-Theme)
BetterQQNT 以后的可玩性肯定会越来越高的！

**Comment by mo-jinran** [comment]
建议将manifest.json的插件信息改成你的

**Comment by MUKAPP** [comment]
> 建议将manifest.json的插件信息改成你的

okk，已经改了
