### ISSUE TITLE
如何正确的从1.0升级到2.0？

### ISSUE THREAD

**Issue by fatinghenji** [mo-jinran/BetterQQNT#5]
我直接按照readme解压了，但是出现了这个错误：
![image](https://github.com/mo-jinran/BetterQQNT/assets/37131177/3da74110-a591-45b0-bc69-c878f2ff7106)

**Comment by Super-XiaoNian** [comment]
我也是，
![image](https://github.com/mo-jinran/BetterQQNT/assets/41782704/558d337b-1b27-4b68-b55b-5585eb959cfa)
有什么bu不对劲吗

**Comment by mo-jinran** [comment]
编辑package.json文件，将main键值改为BetterQQNT（大小写不敏感，请根据项目目录名实际情况修改）

**Comment by mo-jinran** [comment]
不是改成路径，只是改成名字

**Comment by mo-jinran** [comment]
![image](https://github.com/mo-jinran/BetterQQNT/assets/66980784/61e2d3fd-5197-4f8b-9389-db90a570e75c)

**Comment by fatinghenji** [comment]
```json
{
  "name": "qq-chat",
  "version": "9.8.3-13720",
  "private": true,
  "description": "QQ",
  "productName": "QQ",
  "author": {
    "name": "Tencent",
    "email": "QQ-Team@tencent.com"
  },
  "homepage": "https://im.qq.com",
  "sideEffects": true,
  "main": "BetterQQNT",
  "resolutions": {
    "@tencent/dag-utils": "0.6.2"
  },
  "engines": {
    "yarn": ">= 1.22.19"
  },
  "buildVersion": "13720",
  "isPureShell": true,
  "isByteCodeShell": true,
  "platform": "win32",
  "eleArch": "x64"
}
```
更改为上述配置文件后，ntqq成功启动，但是似乎并未成功加载better相关？
![image](https://github.com/mo-jinran/BetterQQNT/assets/37131177/c5e7aa6a-219b-4780-b2fd-9ba2cda03ef0)

**Comment by mo-jinran** [comment]
目前还没做BetterQQNT自己的配置界面（目前没什么能配置的东西
装插件就有插件的配置界面了（但是插件都没适配配置界面

**Comment by fatinghenji** [comment]
1.0时期的koishi功能没有了吗？

**Comment by mo-jinran** [comment]
你说的是另一个团队的BetterQQNT项目，我这个是个人最早做的项目

**Comment by fatinghenji** [comment]
> 你说的是另一个团队的BetterQQNT项目，我这个是个人最早做的项目

抱歉，是我弄混了
