### ISSUE TITLE
Windows QQ 9.8.5-14060 无法调出浏览器控制台

### ISSUE THREAD

**Issue by JoinChang** [mo-jinran/BetterQQNT#8]
NTQQ 版本：`9.8.5-14060`
BetterQQNT 版本：`2.0.0`

复现操作：按下 F12 无任何反应

**Comment by Whuihuan** [comment]
看起来就只有提示，其余的都没能执行

**Comment by mo-jinran** [comment]
QQNT 9.8.5版本暂时无法通过BetterQQNT打开QQNT自身的DevTools
请安装Chii Devtools插件进行远程调试（跟普通的一样，只是功能很少）
Chii DevTools插件仓库地址在插件链接处，请自行根据插件介绍安装

**Comment by FW27623** [comment]
我这貌似还是无法打开，版本是今天推送的14060的修复版14086
node 版本16.15.0
![image](https://github.com/mo-jinran/BetterQQNT/assets/59783568/641fee38-8b13-429a-9beb-38de07ed4d73)

**Comment by JoinChang** [comment]
> 

14086（64位）实测使用 chii-devtools 可以调出控制台。

![image](https://github.com/mo-jinran/BetterQQNT/assets/35451392/88d6e5ae-7c84-4f8e-810f-594745e6385f)
